apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: practice-cluster
  region: us-east-1
  version: "1.28"
nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    ssh:
      allow: true
      publicKeyName: my-key-pair
